# Generated by Django 3.2.25 on 2024-07-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='image',
        ),
    ]
